version: "3"
services:
  app:
    image: kumekay/inlets:latest
    restart: always
    networks:
      - web
      - default
    expose:
      - "9000"
    entrypoint: ["inlets"]
    command:
      - "-server=true"
      - "-port=9000"
      - "-token=[your token]"
    ports:
      - "9000:9000"
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:[example.com]"
      - "traefik.protocol=http"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.port=9000"

networks:
  web:
    external: true
